<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="arthur" name="pytest" skipped="0" tests="19" time="34.650" timestamp="2021-11-15T14:07:37.067878"><testcase classname="tests.test_basic_example" name="test_basic_example" time="2.018" /><testcase classname="tests.test_basic_example" name="test_dryrun_example" time="2.008" /><testcase classname="tests.test_basic_example" name="test_run_sync" time="2.136" /><testcase classname="tests.test_basic_example" name="test_run_reflection" time="2.027" /><testcase classname="tests.test_basic_example" name="test_run_capture" time="2.038" /><testcase classname="tests.test_basic_example" name="test_fixture_reset" time="1.989" /><testcase classname="tests.test_basic_example" name="test_badlog" time="2.241" /><testcase classname="tests.test_basic_example" name="test_release_mode_validation" time="0.026" /><testcase classname="tests.test_basic_example" name="test_multiple_repo_paths_option" time="1.071" /><testcase classname="tests.test_basic_example" name="test_multiple_repo_paths_multiple_options" time="1.245" /><testcase classname="tests.test_basic_example" name="test_multiple_repo_paths_env" time="1.168" /><testcase classname="tests.test_basic_example" name="test_import" time="2.431" /><testcase classname="tests.test_basic_example" name="test_project_no_plugins" time="1.972" /><testcase classname="tests.test_basic_example_v2" name="test_basic_example" time="4.724"><error message="failed on setup with &quot;subprocess.CalledProcessError: Command '['/tmp/tmpm986nbs3/bin/python', '-m', 'inmanta.app', 'module', 'install', '/home/sander/documents/projects/inmanta/pytest-inmanta/examples/testmodulev2']' returned non-zero exit status 1.&quot;">pytestconfig = &lt;_pytest.config.Config object at 0x7f606ffe20f0&gt;

    @pytest.fixture(scope="session")
    def testmodulev2_venv(pytestconfig) -&gt; env.VirtualEnv:
        """
        Yields a Python environment with testmodulev2 installed in it.
        """
        with tempfile.TemporaryDirectory() as venv_dir:
            # set up environment
            venv: env.VirtualEnv = env.VirtualEnv(env_path=venv_dir)
            venv.init_env()
            # workaround for pypa/build#405: unset PYTHONPATH because it's not required in this case and it triggers a bug in build
            with open(os.path.join(venv.site_packages_dir, "usercustomize.py"), "a") as fd:
                fd.write(
                    """
    import os
    
    if "PYTHONPATH" in os.environ:
        del os.environ["PYTHONPATH"]
                    """.strip()
                )
            # install test module into environment
            subprocess.check_call(
                [
                    venv.python_path,
                    "-m",
                    "inmanta.app",
                    "module",
                    "install",
&gt;                   str(pytestconfig.rootpath / "examples" / "testmodulev2"),
                ],
            )

tests/test_basic_example_v2.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['/tmp/tmpm986nbs3/bin/python', '-m', 'inmanta.app', 'module', 'install', '/home/sander/documents/projects/inmanta/pytest-inmanta/examples/testmodulev2'],), kwargs = {}, retcode = 1
cmd = ['/tmp/tmpm986nbs3/bin/python', '-m', 'inmanta.app', 'module', 'install', '/home/sander/documents/projects/inmanta/pytest-inmanta/examples/testmodulev2']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
&gt;           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/tmp/tmpm986nbs3/bin/python', '-m', 'inmanta.app', 'module', 'install', '/home/sander/documents/projects/inmanta/pytest-inmanta/examples/testmodulev2']' returned non-zero exit status 1.

/usr/lib/python3.6/subprocess.py:311: CalledProcessError</error></testcase><testcase classname="tests.test_basic_example_v2" name="test_basic_example_no_install" time="0.059" /><testcase classname="tests.test_handlers" name="test_resource" time="2.929" /><testcase classname="tests.test_handlers" name="test_dryrun" time="2.222" /><testcase classname="tests.test_options" name="test_module_in_place" time="2.174" /><testcase classname="tests.test_options" name="test_not_existing_venv_option" time="0.052" /></testsuite></testsuites>